// Resolve the AI model from env so all tiers stay in sync with deployment config.
const DEFAULT_AI_MODEL = (process.env.OPENAI_MODEL || process.env.OPENROUTER_MODEL || 'ag/claude-sonnet-4-6').trim();

export type BillingTierKey = 'FREE' | 'STARTER' | 'PRO' | 'BUSINESS' | 'ENTERPRISE';

export const BILLING_TIERS: Record<BillingTierKey, any> = {
  FREE: {
    monthlyLimits: {
      ARTICLE_GENERATION: 5,
      INSTAGRAM_GENERATION: 10,
      VIDEO_LIGHT: 3,
      IMAGE_GENERATION: 2,
      VIDEO_HEAVY: 0,
      MOTION_RENDER: 0,
    },
    monthlyTokens: 0,
    maxWpSites: 1,
    aiModel: DEFAULT_AI_MODEL,
    canAutoSync: false,
    minSyncInterval: 0,
    canAccessViewBoost: false,
    canAnalyzeTrends: false,
  },
  STARTER: {
    monthlyLimits: {
      ARTICLE_GENERATION: 40,
      INSTAGRAM_GENERATION: 100,
      VIDEO_LIGHT: 20,
      IMAGE_GENERATION: 8,
      VIDEO_HEAVY: 2,
      MOTION_RENDER: 2,
    },
    monthlyTokens: 0,
    maxWpSites: 2,
    aiModel: DEFAULT_AI_MODEL,
    canAutoSync: true,
    minSyncInterval: 120,
    canAccessViewBoost: false,
    canAnalyzeTrends: true,
    price: 99000,
  },
  PRO: {
    monthlyLimits: {
      ARTICLE_GENERATION: 150,
      INSTAGRAM_GENERATION: 300,
      VIDEO_LIGHT: 80,
      IMAGE_GENERATION: 30,
      VIDEO_HEAVY: 12,
      MOTION_RENDER: 8,
    },
    monthlyTokens: 0,
    maxWpSites: 5,
    aiModel: DEFAULT_AI_MODEL,
    canAutoSync: true,
    minSyncInterval: 60,
    canAccessViewBoost: true,
    canAnalyzeTrends: true,
    price: 399000,
  },
  BUSINESS: {
    monthlyLimits: {
      ARTICLE_GENERATION: 400,
      INSTAGRAM_GENERATION: 800,
      VIDEO_LIGHT: 200,
      IMAGE_GENERATION: 100,
      VIDEO_HEAVY: 40,
      MOTION_RENDER: 30,
    },
    monthlyTokens: 0,
    maxWpSites: 10,
    aiModel: DEFAULT_AI_MODEL,
    canAutoSync: true,
    minSyncInterval: 15,
    canAccessViewBoost: true,
    canAnalyzeTrends: true,
    price: 999000,
  },
  ENTERPRISE: null,
};
BILLING_TIERS.ENTERPRISE = BILLING_TIERS.BUSINESS;

export const FEATURE_TO_CATEGORY: Record<string, string> = {
  ARTICLE_GENERATION: 'ARTICLE_GENERATION',
  INSTAGRAM_GENERATION: 'INSTAGRAM_GENERATION',
  STORYBOARD_GENERATION: 'INSTAGRAM_GENERATION',
  HASHTAG_GENERATION: 'INSTAGRAM_GENERATION',
  VIDEO_GENERATION: 'VIDEO_LIGHT',
  VIDEO_SCRIPT: 'VIDEO_LIGHT',
  ALTERNATE_HOOKS: 'VIDEO_LIGHT',
  BROLL_KEYWORDS: 'VIDEO_LIGHT',
  SUGGEST_FOOTAGE_KEYWORDS: 'VIDEO_LIGHT',
  TTS_PREVIEW: 'VIDEO_LIGHT',
  TTS_VOICEOVER: 'VIDEO_LIGHT',
  REGENERATE_FIELD: 'VIDEO_LIGHT',
  REGENERATE_VOICEOVER: 'VIDEO_LIGHT',
  IMPROVE_VISUAL: 'VIDEO_LIGHT',
  AUDIO_TRANSCRIPTION: 'VIDEO_HEAVY',
  AUTO_CUTAWAY: 'VIDEO_HEAVY',
  VIDEO_ANALYSIS: 'VIDEO_HEAVY',
  VIDEO_EXPORT: 'VIDEO_HEAVY',
  IMAGE_GENERATION: 'IMAGE_GENERATION',
  SLIDE_IMAGE: 'IMAGE_GENERATION',
  THUMBNAIL_GENERATION: 'IMAGE_GENERATION',
  TEXT_OVERLAY: 'IMAGE_GENERATION',
  MOTION_GRAPHICS_RENDER: 'MOTION_RENDER',
  MOTION_GRAPHICS_PNG_RENDER: 'MOTION_RENDER',
};

export const KREDIT_COSTS: Record<string, number> = {
  ARTICLE_GENERATION: 3,
  STORYBOARD_GENERATION: 3,
  VIDEO_SCRIPT: 3,
  HASHTAG_GENERATION: 1,
  ALTERNATE_HOOKS: 1,
  BROLL_KEYWORDS: 1,
  SUGGEST_FOOTAGE_KEYWORDS: 1,
  AUTO_CUTAWAY: 2,
  TTS_PREVIEW: 1,
  TTS_VOICEOVER: 5,
  REGENERATE_FIELD: 1,
  REGENERATE_VOICEOVER: 1,
  IMPROVE_VISUAL: 1,
  IMAGE_GENERATION: 5,
  SLIDE_IMAGE: 3,
  THUMBNAIL_GENERATION: 3,
  MOTION_GRAPHICS_RENDER: 30,
  MOTION_GRAPHICS_PNG_RENDER: 3,
  TEXT_OVERLAY: 2,
  VIDEO_ANALYSIS: 50,
  VIDEO_EXPORT: 30,
  AUDIO_TRANSCRIPTION: 10,
};

// Backward compatibility for legacy call sites while they migrate to ensureBilling().
export const TOKEN_COSTS = KREDIT_COSTS;
