ALTER TABLE script_project
ADD COLUMN IF NOT EXISTS headline VARCHAR(255),
ADD COLUMN IF NOT EXISTS sub_headline VARCHAR(255),
ADD COLUMN IF NOT EXISTS caption TEXT,
ADD COLUMN IF NOT EXISTS hook TEXT,
ADD COLUMN IF NOT EXISTS thumbnail_prompt TEXT,
ADD COLUMN IF NOT EXISTS music_suggestion TEXT,
ADD COLUMN IF NOT EXISTS hashtags JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS target_duration_seconds INTEGER;

ALTER TABLE script_scene
ADD COLUMN IF NOT EXISTS footage_searches JSONB DEFAULT '[]'::jsonb;
